#ifndef __NOTIF_VALUE_H
#define __NOTIF_VALUE_H


/*CategoryID Values*/
#define CATEGORYID_OTHER 0
#define CATEGORYID_INCOMINGCALL 1
#define CATEGORYID_MISSEDCALL 2
#define CATEGORYID_VOICEMAIL 3
#define CATEGORYID_SOCIAL 4
#define CATEGORYID_SCHEDULE 5
#define CATEGORYID_EMAIL 6
#define CATEGORYID_NEWS 7
#define CATEGORYID_HEALTHANDFITNESS 8
#define CATEGORYID_BUSINESSANDFINANCE 9
#define CATEGORYID_LOCATION 10
#define CATEGORYID_ENTERTAINMENT 11






/*EventID Values*/
#define EVENTID_NOTIFICATION_ADDED 0
#define EVENTID_NOTIFICATION_MODIFIED 1
#define EVENTID_NOTIFICATION_REMOVED 2





/*CommandID Values*/
#define COMMANDID_GETNOTIFICATION_ATTRIBUITES 0
#define COMMANDID_GETAPP_ATTRIBUITES 1
#define COMMANDID_PERFORM_NOTIFICATION_ACTION 2




/*NotificationAttributeID Values*/
#define NOTIFICATION_ATTRIBUITE_ID_APPIDENTIFIER 0
#define NOTIFICATION_ATTRIBUITE_ID_TITLE 1
#define NOTIFICATION_ATTRIBUITE_ID_SUBTITLE 2
#define NOTIFICATION_ATTRIBUITE_ID_MESSAGE 3
#define NOTIFICATION_ATTRIBUITE_ID_MESSAGESIZE 4
#define NOTIFICATION_ATTRIBUITE_ID_DATE 5
#define NOTIFICATION_ATTRIBUITE_ID_POSITIVEACTIONLABLE 6
#define NOTIFICATION_ATTRIBUITE_ID_NEGATIVEACTIONLABLE 7


/*mask of NotificationAttributeID*/
#define FLAG_APPID 0x0001
#define FLAG_TITLE 0x0002
#define FLAG_SUBTITLE 0x0004
#define FLAG_MESSAGE 0x0008
#define FLAG_MESGSIZE 0x0010
#define FLAG_DATE 0x0020
#define FLAG_POS_ACT_LAB 0x0040
#define FLAG_NEG_ACT_LAB 0x0080


/*capacity*/
#define APPID_CAP 100 
#define TITLE_CAP 50
#define SUBTITLE_CAP 100
#define MSG_CAP 248
#define MSG_SIZE_CAP 10
#define DATE_CAP 10
#define POS_CAP 10
#define NEG_CAP 10


/*ActionID Values*/
#define ACTION_ID_POSITIVE 0
#define ACTION_ID_NEGATIVE 1




/*AppAttributeID Values*/

#define APP_ATTRIBUTE_ID_DISPLAYNAME 0








#define DATA_LENGTH 2048
#define ORI_BUF_SIZE 3
#define MAX_PARTS_TIMEOUT 100000  /*100ms*/
#define CMD_ID_LENGTH 1
#define NOTIF_UID_LENGTH 4
#define ATTR_UNIT_LENGTH 3
#define NOTIF_REQ_LENGTH 64

#ifndef DEBUG
#define DEBUG printf
#endif/*DEBUG*/







#endif  /*__NOTIF_VALUE_H*/

